### ISSUE TITLE
Update site.enddate to be April 3, 2016

### ISSUE THREAD

**Issue by groovecoder** [jugisahunk/200OK_CFP#1]
The site currently says submissions are accepted until June 3. But we need to have all submissions by March 31 so we can select proposals and set the final agenda by April 15, and book any necessary speaker travel by June 3.

I didn't see "June 3" anywhere in the codebase, so I assume it's in a production config file on the box itself?

**Comment by jugisahunk** [comment]
I've made the update to "development.yml" and I've updated the .gitignore to add that file in the repo. I had some trouble updated the app to "production.yml" so it's still stuck on development.
